### ISSUE TITLE
Interpolation escaping

### ISSUE THREAD

**Issue by nicknovitski** [LnL7/vim-nix#11]
While working on a nix expression containing a multi-line string which contains a bash script which outputs a nix expression which contains single-line strings which have interpolations (phew!), I noticed that interpolations are always highlighted, even when they've been escaped.

```
{
  singleline = "${shouldBeHighlighted}\${shouldNotBe}";
  multiline = ''
    ${shouldBeHighlighted}
    ''${shouldNotBe}
  '';
}
```

**Comment by LnL7** [comment]
Either I'm not understanding the issue correctly or the plugin is not getting loaded correctly (I've had issue with `vim_configurable` before). The example looks fine good to me.

<img width="450" alt="screen shot 2017-04-03 at 20 33 41" src="https://cloud.githubusercontent.com/assets/689294/24624988/e0df31f0-18ad-11e7-8090-58fd5c2ce375.png">

**Comment by nicknovitski** [comment]
Hmmmm!  That is quite unsettling.  I am using vim_configurable.  I'll look into the problem.

Thanks for your efforts. :)

**Comment by nicknovitski** [comment]
Wow, you're totally right, I've been working with fake syntax highlighting this whole time.

It's very strange: my installations of elm-vim and rust.vim are not subject to the same problem, but I can't figure out what's different about them.

**Comment by LnL7** [comment]
`vim_configurable` includes some [minimal syntax highlighting](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/vim/configurable.nix#L148-L149) for nix by default. That seems to cause conflicts in some cases, but I'm still not sure when this happens.

**Comment by nicknovitski** [comment]
Wooooah so it applies [this patch](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/vim/ft-nix-support.patch) before loading any other plugins?  That sure seems like it could cause a conflict.

And indeed, if I set `vim.ftNix = false;` in my `~/.nixpkgs/config.nix`, then recompile vim without that "patch," then I actually get to see your plugin!  Good grief!  It's perfect!
