### ISSUE TITLE
Unexpected unindent on inherit

### ISSUE THREAD

**Issue by lheckemann** [LnL7/vim-nix#12]
If I'm writing let bindings using the `inherit` keyword, it gets unindented one level — presumably because that's the behaviour for the `in` keyword which is a prefix of `inherit`. Would it be possible to get that unindent to only happen once a space has been added after `in`?

**Comment by LnL7** [comment]
The in keyword isn't necessarily followed by a space. I remember trying to make this work for both in and inherit when implementing it, but I couldn't find a way to trigger the indentation correctly for both cases while the user is still typing.

```
let
  foo = 42;
  in
    ^ cursor, in<Return> or inherit?
```
