### ISSUE TITLE
visual block insert broken by indent behavior?

### ISSUE THREAD

**Issue by dtzWill** [LnL7/vim-nix#13]
I created a minimal config using only "vim-nix" and `vim.ftNix = false`, so hopefully this is reproducible.
Does not occur when haven't loaded "vim-nix".

## Steps

* Save this as "test.nix":
```nix
{
  a =
    if true then "a"
            else "b";
}
```
* `$ vim test.nix`
* `2j4l` (move cursor to the 'i' in the "if")
* `^vjI# <esc><esc>' ("control-v" for visual block mode, "j" move cursor down, "I" (capital 'i') to start inserting on multiple lines, "# " (text to insert), "<esc><esc>" -- exit insert mode.

(This is very similar to the example here: http://vim.wikia.com/wiki/Inserting_text_in_multiple_lines)

### Result with vim-nix
```nix
{
  a =
  # if true then "a"
            else "b";
}
```

### Result without vim-nix (what I intend/expect)
```nix
{
  a =
    # if true then "a"
    #         else "b";
}
```

**Comment by dtzWill** [comment]
Are you able to reproduce? Just want to check before letting this sit too long. :)

**Comment by LnL7** [comment]
Not yet, but it's on my todo list.

**Comment by dtzWill** [comment]
Repro: https://gist.github.com/dtzWill/e32fc48f44d4f1ca3b5c3c99c895901a


```console
$ nix build '(import (fetchGit https://gist.github.com/e32fc48f44d4f1ca3b5c3c99c895901a.git) {})' 
$ cat result                                                                                                                                                                      14:28:33 on 18-02-23
3,4c3,4
<   #  if true then "a"
<              else "b";
---
>     #  if true then "a"
>     #          else "b";
$
```
Hope this helps!

And "hooray" it's not just me.

**Comment by LnL7** [comment]
Also added a test that reproduces the issue in https://github.com/LnL7/vim-nix/commit/36c5feb514930e8fb8e2f4567d6b0d9e806fc2eb.
