### ISSUE TITLE
wonky highlighting in networkmanager.nix

### ISSUE THREAD

**Issue by teto** [LnL7/vim-nix#15]
Thanks for the plugin !
with nvim 0.2.2 and nixos-unstable:
 https://github.com/teto/nixpkgs/blob/56b69393e037ad812fd06a742b5c1986c8bc7b8a/nixos/modules/services/networking/networkmanager.nix#L300
![selection_001](https://user-images.githubusercontent.com/886074/38921299-5fb3b3c2-4330-11e8-990b-e84c07d401ce.png)
(at some point everything is highlighted as a string)

**Comment by LnL7** [comment]
Nice catch. I think the specific problem is `attrs.${foo.bar}` or probably any complex expression in an attribute interpolation.
