### ISSUE TITLE
iskeyword: do we really need to set this sensitive parameter inside the plugin itself

### ISSUE THREAD

**Issue by ivankovnatsky** [LnL7/vim-nix#35]
@LnL7 thank you for this plugin.

maybe that just me, but i can not overcome dash/hyphen being a part of word, especially when moving with `w` `b` and others.

```
  iskeyword=@,48-57,_,192-255,-
        Last set from /nix/store/1yvb8rqfsqxbb3683g2mkhm558gf6xac-vimplugin-vim-nix-2020-06-23/share/vim-plugins/vim-nix/ftplugin/nix.vim line 14
```

again, this is opinionated, but i would not set this even for only *.nix files.

**Comment by bew** [comment]
Why close @sevenfourk?
