### ISSUE TITLE
vim-nix breaks backspace key

### ISSUE THREAD

**Issue by nh2** [LnL7/vim-nix#38]
Using this on NixOS 20.09 (commit `b94726217f7):

```nix
{
    # From https://nixos.wiki/wiki/Editor_Modes_for_Nix_Files#vim-nix
    (pkgs.vim_configurable.customize {
      name = "vim";
      vimrcConfig.packages.myplugins = with pkgs.vimPlugins; {
        start = [ vim-nix ]; # load plugin on startup
      };
    })
}
```

breaks the Backspace and delete keys in vim (they simply have no effect, even in new plain sessions opened with `vim`).

`vim_configurable` without plugin does not have that issue.

What's going on?

**Comment by LnL7** [comment]
I see the same behaviour without `vim-nix` so whatever this is it looks like a nixpkgs issue.

**Comment by nh2** [comment]
@LnL7 can you clarify what exactly "without `vim-nix`" means here? Do you mean removing `vim-nix` from `start = [ ]`, or using just `vim_configurable` without `.customize`?

Because I have tried the latter but not yet the former.
