### ISSUE TITLE
Add a license to the repository.

### ISSUE THREAD

**Issue by aszlig** [LnL7/vim-nix#4]
This might be a good idea for future contributions :-)

As for my contributions you're free to choose the license as long as it isn't a proprietary one.

**Comment by aszlig** [comment]
@LnL7: @domenkozar suggested to merge it into `<nixpkgs>`, would you mind releasing your code under the [same license as `<nixpkgs>`](https://github.com/NixOS/nixpkgs/blob/master/COPYING)?

**Comment by LnL7** [comment]
I should defiantly add an entry to vimPlugins. But I'm not sure how I feel about moving everything there since it's pretty that's a pretty large repository, what would the advantage be?

**Comment by aszlig** [comment]
@LnL7: We already patch in a [syntax file](https://github.com/NixOS/nixpkgs/blob/248cbef4d34ec874bb44f6a825fb88421a63c640/pkgs/applications/editors/vim/ft-nix-support.patch) by default for `vim_configurable`, so it might be a good idea to improve it.

Another advantage of this would be that we could generate the syntax file using Nix itself, so we are always up-to-date when it comes to things like builtin functions. Also, it would make the syntax file less cluttered because we're no longer limited to VimL and thus are able to easily compose regular expressions.

**Comment by LnL7** [comment]
That's an interesting idea, I would like to keep this repository for "regular use", but we could move the source to nixpkgs and keep this repository up to date with the output from nix.

**Comment by LnL7** [comment]
fixed in 7a1b72d
