### ISSUE TITLE
Upstream syntax highlighting?

### ISSUE THREAD

**Issue by jsoo1** [LnL7/vim-nix#47]
Hello! Thank you for vim-nix! Would you be alright if someone were to try to upstream the syntax highlighting from your plugin into `{neo,}vim`?

**Comment by jsoo1** [comment]
According to [the vim documentation on the subject](https://github.com/vim/vim/blob/master/runtime/syntax/README.txt) some maintainer would be listed at the top of the syntax file who would send updated versions to Bram.  For example, see [the haskell syntax file](https://github.com/vim/vim/blob/master/runtime/syntax/haskell.vim).

**Comment by jsoo1** [comment]
I think if enough time goes by I will put in a patch to the vim tree naming you @equill as the point of contact. Because this plugin is MIT licensed I believe it should suffice to keep a copy of the license and attribution to LnL7 in the upstream patch.

**Comment by equill** [comment]
That works for me. Just give me a heads-up when you've done it, and I'll pick it up from there.

**Comment by jsoo1** [comment]
As of https://github.com/vim/vim/commit/86b4816766d976a7ecd4403eca1f8bf6b4105800 the syntax from vim-nix is in the vim tree.  Thank you again to @equill and @LnL7 .

**Comment by LnL7** [comment]
Thanks for looking into this! I thought about this at some point but that was rather early on and I figured somebody would make a better package at some point 😁 since there are still some problems with indentation.

Some thoughts:
Depending on what gets added to vim-nix, it might make sense to only upstream the syntax/indentation and not commands, etc. No idea what the approach is for upstream vim.
Once nixpkgs is updated it might be good to get rid of some of the extra customization that happens there, nog sure if that's still in place.

**Comment by jsoo1** [comment]
> Thanks for looking into this! I thought about this at some point but that was rather early on and I figured somebody would make a better package at some point 😁 since there are still some problems with indentation.

You're welcome and thank you for all your work in the nix ecosystem!

I am pretty sure `vim-nix` remains the de-facto standard 😄.  Ah, how software evolves, huh?

Not to worry, though, only the syntax highlighting made it upstream.  Though indentation could be nice, should it get fixed 😃.

> Some thoughts: Depending on what gets added to vim-nix, it might make sense to only upstream the syntax/indentation and not commands, etc. 

I agree. I'm not even sure what kind of commands and extras would be accepted upstream.

> No idea what the approach is for upstream vim. Once nixpkgs is updated it might be good to get rid of some of the extra customization that happens there, nog sure if that's still in place.

Good call. I can't recall but I did see one recent PR which spurred some of this work.
